server:
  port: 9090
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/springweb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
